---
title: "HW_1"
---

```{r}
#Q1
library(ggplot2)
library(readr)
library(dplyr)

ncdc_temp <- read_csv("https://bcdanl.github.io/data/ncdc_temp_cleaned.csv")

ncdc_temp$month <- factor(ncdc_temp$month, levels = sprintf("%02d", 1:12), 
                          labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))

monthly_avg_temp <- ncdc_temp %>%
  group_by(month, location) %>%
  summarise(avg_temp = mean(temperature, na.rm = TRUE))

filtered_points <- monthly_avg_temp %>% filter(month %in% c("Jan", "Apr", "Jul", "Oct"))

ggplot(monthly_avg_temp, aes(x = month, y = avg_temp, color = location, group = location)) +
  geom_line(size = 1) + 
  geom_point(data = filtered_points, aes(x = month, y = avg_temp), size = 0.5, color = "black") + 
  scale_x_discrete(breaks = c("Jan", "Apr", "Jul", "Oct"), labels = c("Jan", "Apr", "Jul", "Oct")) + 
  labs(x = "Month", y = "Temperature (°F)", title = "Monthly Average Temperature by Location") +
  theme_minimal()


```

```{r}
#Q2
library(tidyverse)

ncdc_temp <- read_csv(
 'https://bcdanl.github.io/data/ncdc_temp_cleaned.csv')

ncdc_temp$month <- factor(ncdc_temp$month, levels = sprintf("%02d", 1:12))


ggplot(ncdc_temp, aes(x = month, y = temperature)) +  
  geom_boxplot(fill = "lightgray", color = "black") +  
  scale_y_continuous(breaks = seq(40, 100, 20), limits = c(20, 100)) +
  labs(
    title = "",
    x = "month",
    y = "mean temperature (°F)"  
  ) +
  theme_bw() +
  theme(
    panel.grid.major.y = element_line(color = "lightgray", linetype = "dotted"),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_line(color = "black"),
    axis.ticks.length.x = unit(0.2, "cm"),
    text = element_text(size = 11)
  )

```

```{r}
#Q3
library(tidyverse)
library(ggridges)

ncdc_temp <- read_csv(
 'https://bcdanl.github.io/data/ncdc_temp_cleaned.csv')

monthly_mean_temp <- ncdc_temp %>% 
  group_by(month) %>% 
  summarise(mean_temp = mean(temperature, na.rm = TRUE))

ggplot(ncdc_temp, aes(x = temperature, y = factor(month))) +
  geom_density_ridges(scale = 2, fill = 'lightblue', linetype = "blank") +
  labs(x = "mean temperature (°F)", y = "month") +
  theme_minimal()

```

```{r}
#Q4
library(ggplot2)
data(mtcars)

ggplot(mtcars, aes(x = disp, y = mpg, color = hp)) +
  geom_point() +
  scale_color_gradient(low = "navy", high = "lightblue") +
  labs(x = "displacement(cu. in.)", y = "fuel efficiency(mpg)", color = "hp") +
  theme_minimal()


```

```{r}
#Q5
library(tidyverse)

popgrowth_df <- read_csv(
  'https://bcdanl.github.io/data/popgrowth.csv')
popgrowth_df <- popgrowth_df %>% 
  mutate(popgrowth = (pop2010 - pop2000) / pop2000 * 100)

ggplot(popgrowth_df, aes(x = reorder(state,popgrowth), y = popgrowth, fill = region)) + 
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs( x = " reorder(state, popgrowth)", y = "population growth, 2000 to 2010", fill = "region") +
  theme_minimal()

```

```{r}
#Q6
library(tidyverse)
male_Aus <- read_csv(
  'https://bcdanl.github.io/data/aus_athletics_male.csv')

ggplot(male_Aus, aes (x = height, y = pcBfat, shape = sport, color = sport)) +
  geom_point(size = 3, alpha = 0.7) +
  scale_shape_manual( values = c( "basketball" = 16, "field" = 15, "swimming" = 18, "track" = 17, "water polo" = 25)) +
  scale_color_manual(values = c("basketball" = "darkred", "field" = "grey", "swimming" = "grey", "track" = "grey", "water polo" = "grey")) +
  labs(x = "height(cm)", y = "% body fat", shape = "sport", color = "sport") +
  theme_minimal()


```

```{r}
#Q7

titanic <- read_csv(
  'https://bcdanl.github.io/data/titanic_cleaned.csv')

titanic_female <- titanic %>% 
  mutate(gender = "female", gender_new = "all passengers")

titanic_male <- titanic %>% 
  mutate(gender = "male", gender_new = "all     passengers")

titanic_2x <- titanic_male %>% 
  rbind(titanic_female)

titanic <- titanic %>% 
  mutate(gender_new = gender)

  ggplot(data = titanic,
         aes(x = age, y = after_stat(count), fill = gender_new)) +
  geom_density(data = titanic_2x, color = NA) +
    geom_density(color = NA) +
  facet_wrap(~gender) +
    scale_fill_manual(values = c("all passengers" = "lightgray", "female" = "darkorange", "male" = "darkblue"), labels = c("all passengers", "females", "males")) +
    theme_minimal() +
    theme(legend.position = "bottom") +
    labs(fill = "")

```

```{r}
#Q8
library(tidyverse)
library(ggplot2)
library(readr)


cows_filtered <- read_csv("https://bcdanl.github.io/data/cows_filtered.csv")

ggplot(cows_filtered, aes(x = butterfat, fill = breed, color = breed)) +
  geom_density(alpha = 0.3) +
  labs(x = "butterfat contents", y = "density") +
  theme_minimal()

```

```{r}
#Q9
#@s1arkey
```

